// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pztwswvhxsidiunaqvxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dHdzd3ZoeHNpZGl1bmFxdnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDQ3NjQsImV4cCI6MjA2MDE4MDc2NH0.L1upTyiMEcysAb2QHjFpi4TPaFusrGwjGCEXoIrTBCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);